apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /mnt/freeday
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: minikube.k8s.io/name
          operator: In
          values:
          - minikube
