apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-sts
  labels:
    app: mongo
spec:
  replicas: 3
  # Needed for StatefulSet
  serviceName: mongo
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: freeday-mongo
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        volumeMounts:
        - mountPath: /data/db
          name: app-data
  # Needed for StatefulSet
  volumeClaimTemplates:
  - metadata:
      name: app-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: local-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  # If you went to go back to Deployment, uncomment the line below and delete ClusterIP: None
  # Type: ClusterIP
  clusterIP: None
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
